### ISSUE TITLE
Integer Increment

### ISSUE THREAD

**Issue by ethicalhack3r** [alexlauerman/IncrementMePlease#1]
First of all, thank you for this extension, I find it useful quite often during tests.

However, I think it would be better if the incrementation was just an integer.

Currently the incremented payload looks like this `Incremented8073` (a string and an integer).

I think it would be more useful if the incrementation was only an integer (no string), and started from `0` and incremented from there (just the `[Counter]` part).

Using just an integer would help when the application is validating for int types, and starting from `0`, just makes more sense, I think?

Thanks again.

**Comment by alexlauerman** [comment]
Thanks for the feedback!

That does make sense. I'm not sure that it's always going to better. It's kind of nice seeing the string, but not necessary, and you could always prefix your own string. I suppose having an actual UI would be ideal. 

Either way, it's a very easy change. I can make the change and rebuild if you want. As a workaround, you could use an upstream proxy with a match/replace rule to remove the "Incremented".

**Comment by ethicalhack3r** [comment]
Thanks for the quick response Alex!

Yea, having looked at the codebase it looks like a simple change to this line https://github.com/alexlauerman/IncrementMePlease/blob/fd2e7d86998af8a364a916cd15458dd778ce447e/src/burp/BurpExtender.java#L63

But, my Java skills are zero, so currently looking into how I compile it on macOS after making the desired change...

A UI would be ideal, but probably a lot more work.

It's up to you if you want to make the change, or not, if you think one way is better than the other. Personally, I think just the counter will fit in more cases than the current method, as it can be used for both integers and strings.

Thanks again.

**Comment by michalogorzalek5** [comment]
Hi, is it possible @alexlauerman to place the new version in the BApps Store?

Michał

**Comment by alexlauerman** [comment]
@michalogorzalek5 I've built this release based on the latest code and submitted it to the BApp store.

**Comment by alexlauerman** [comment]
The contributions from @xl-sec (version 1.1) are now in the is in the BApp store which resolves this request.
